version: "3.4"

services:
  elixir-custom:
    image: elixir-custom
    build: .
    environment:
      - TEST_SERVER_HOST
    command: |
      mix test --cover --export-coverage default
      mix test.coverage
    tty: true
    volumes:
      - ./:/var/www/html
